title: "Subhankar Nag"
description: "PhD student in Deep Learning"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache


author:
  name: "Subhankar Nag"
  avatar: "/assets/images/iitb_dp_1.png" # optional
  bio: "PhD Student, Deep Learning"
  location: "India"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:snag081@email.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/subhankarnag"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/..."


# Sidebar settings
author_profile: true
minimal_mistakes_skin: "default"  # or "air", "contrast", "dark"


# Navigation
nav:
  - title: "About"
    url: /about/
  - title: "Publications"
    url: /publications/
  - title: "Projects"
    url: /projects/
  - title: "CV"
    url: /cv/